# Generated by Django 3.0.4 on 2020-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localShop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sname',
            new_name='house',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shop_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
