# Generated by Django 3.0.4 on 2020-05-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localShop', '0002_auto_20200501_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
