# Generated by Django 3.0.4 on 2020-05-01 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=200)),
                ('sname', models.CharField(default='', max_length=200)),
                ('town', models.CharField(default='', max_length=200)),
                ('pincode', models.CharField(default='', max_length=12)),
                ('phone', models.CharField(default='', max_length=12)),
                ('is_store', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=200)),
                ('img', models.ImageField(default='default.jpg', upload_to='localshop/pics')),
                ('is_active', models.BooleanField(default=True)),
                ('license_no', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
